### ISSUE TITLE
Traceback errors in web app

### ISSUE THREAD

**Issue by fredclausen** [fredclausen/docker-acarshub#5]
```
[vdlm2dec] 2020/12/08 17:01:58 {"timestamp":1607446918.0912049,"station_id":"CS-KABQ-VDLM","channel":2,"freq":136.975,"icao":10580652,"toaddr":1057098,"is_response":1,"is_onground":2}
[webapp] 2020/12/08 17:01:58 [vdlm2 data] b'{"timestamp":1607446918.0912049,"station_id":"CS-KABQ-VDLM","channel":2,"freq":136.975,"icao":10580652,"toaddr":1057098,"is_response":1,"is_onground":2}\n'
[webapp] 2020/12/08 17:02:00 Exception in thread Thread-4:
[webapp] 2020/12/08 17:02:00 Traceback (most recent call last):
[webapp] 2020/12/08 17:02:00   File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
[webapp] 2020/12/08 17:02:00     self.run()
[webapp] 2020/12/08 17:02:00   File "/usr/lib/python3.7/threading.py", line 865, in run
[webapp] 2020/12/08 17:02:00     self._target(*self._args, **self._kwargs)
[webapp] 2020/12/08 17:02:00   File "/webapp/application.py", line 333, in acarsGenerator
[webapp] 2020/12/08 17:02:00     acars_json = json.loads(data)
[webapp] 2020/12/08 17:02:00   File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
[webapp] 2020/12/08 17:02:00     return _default_decoder.decode(s)
[webapp] 2020/12/08 17:02:00   File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
[webapp] 2020/12/08 17:02:00     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[webapp] 2020/12/08 17:02:00   File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
[webapp] 2020/12/08 17:02:00     obj, end = self.scan_once(s, idx)
[webapp] 2020/12/08 17:02:00 json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 218 (char 217)
[webapp] 2020/12/08 17:02:00 Invalid session 52a6914f421048ceb70871b73bca5779 (further occurrences of this error will be logged with level INFO)
[vdlm2dec] 2020/12/08 17:02:01 {"timestamp":1607446921.0073659,"station_id":"CS-KABQ-VDLM","channel":2,"freq":136.975,"fromaddr":2132536,"icao":16777215,"is_response":0,"is_onground":2}
```

```
[webapp] 2020/12/08 19:37:36 [vdlm2 data] b'{"timestamp":1607456256.529736,"station_id":"CS-KABQ-VDLM","channel":2,"freq":136.975,"icao":11269048,"toaddr":1053386,"is_response":0,"is_onground":0,"mode":"2","label":"H1","block_id":"5","ack":"!","tail":"N8698B","flight":"WN3630","msgno":"F03A","text":"#M1B/B6 QXHADS2.ADS.N8698B034E07193B5D963A8762633C0FD553"}\n'
[vdlm2dec] 2020/12/08 19:37:38 {"timestamp":1607456258.4958191,"station_id":"CS-KABQ-VDLM","channel":2,"freq":136.975,"icao":11269048,"toaddr":1053386,"is_response":1,"is_onground":0}
[webapp] 2020/12/08 19:37:38 [vdlm2 data] b'{"timestamp":1607456258.4958191,"station_id":"CS-KABQ-VDLM","channel":2,"freq":136.975,"icao":11269048,"toaddr":1053386,"is_response":1,"is_onground":0}\n'
[vdlm2dec] 2020/12/08 19:37:41 {"timestamp":1607456261.020283,"station_id":"CS-KABQ-VDLM","channel":2,"freq":136.975,"icao":10618714,"toaddr":1057098,"is_response":1,"is_onground":0}
[webapp] 2020/12/08 19:37:41 [vdlm2 data] b'{"timestamp":1607456261.020283,"station_id":"CS-KABQ-VDLM","channel":2,"freq":136.975,"icao":10618714,"toaddr":1057098,"is_response":1,"is_onground":0}\n'
[webapp] 2020/12/08 19:37:45 Exception in thread Thread-4:
[webapp] 2020/12/08 19:37:45 Traceback (most recent call last):
[webapp] 2020/12/08 19:37:45   File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
[webapp] 2020/12/08 19:37:45     self.run()
[webapp] 2020/12/08 19:37:45   File "/usr/lib/python3.7/threading.py", line 865, in run
[webapp] 2020/12/08 19:37:45     self._target(*self._args, **self._kwargs)
[webapp] 2020/12/08 19:37:45   File "/webapp/application.py", line 358, in acarsGenerator
[webapp] 2020/12/08 19:37:45     acars_json = json.loads(data)
[webapp] 2020/12/08 19:37:45   File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
[webapp] 2020/12/08 19:37:45     return _default_decoder.decode(s)
[webapp] 2020/12/08 19:37:45   File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
[webapp] 2020/12/08 19:37:45     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[webapp] 2020/12/08 19:37:45   File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
[webapp] 2020/12/08 19:37:45     obj, end = self.scan_once(s, idx)
[webapp] 2020/12/08 19:37:45 json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 217 (char 216)
[webapp] 2020/12/08 19:37:45 [2020-12-08 19:37:45 +0000] [370] [ERROR] Socket error processing request.
[webapp] 2020/12/08 19:37:45 Traceback (most recent call last):
[webapp] 2020/12/08 19:37:45   File "/usr/lib/python3/dist-packages/gunicorn/workers/sync.py", line 134, in handle
[webapp] 2020/12/08 19:37:45     req = six.next(parser)
[webapp] 2020/12/08 19:37:45   File "/usr/lib/python3/dist-packages/gunicorn/http/parser.py", line 41, in __next__
[webapp] 2020/12/08 19:37:45     self.mesg = self.mesg_class(self.cfg, self.unreader, self.req_count)
[webapp] 2020/12/08 19:37:45   File "/usr/lib/python3/dist-packages/gunicorn/http/message.py", line 181, in __init__
[webapp] 2020/12/08 19:37:45     super(Request, self).__init__(cfg, unreader)
[webapp] 2020/12/08 19:37:45   File "/usr/lib/python3/dist-packages/gunicorn/http/message.py", line 54, in __init__
[webapp] 2020/12/08 19:37:45     unused = self.parse(self.unreader)
[webapp] 2020/12/08 19:37:45   File "/usr/lib/python3/dist-packages/gunicorn/http/message.py", line 230, in parse
[webapp] 2020/12/08 19:37:45     self.headers = self.parse_headers(data[:idx])
[webapp] 2020/12/08 19:37:45   File "/usr/lib/python3/dist-packages/gunicorn/http/message.py", line 74, in parse_headers
[webapp] 2020/12/08 19:37:45     remote_addr = self.unreader.sock.getpeername()
[webapp] 2020/12/08 19:37:45 OSError: [Errno 107] Transport endpoint is not connected
[vdlm2dec] 2020/12/08 19:37:55 {"timestamp":1607456275.2244761,"station_id":"CS-KABQ-VDLM","channel":2,"freq":136.975,"icao":11264117,"toaddr":1066154,"is_response":0,"is_onground":0,"mode":"2","label":"_d","block_id":"2","ack":"C","tail":"N8643A","flight":"WN4667","msgno":"S35A"}
[webapp] 2020/12/08 19:37:55 [vdlm2 data] b'{"timestamp":1607456275.2244761,"station_id":"CS-KABQ-VDLM","channel":2,"freq":136.975,"icao":11264117,"toaddr":1066154,"is_response":0,"is_onground":0,"mode":"2","label":"_d","block_id":"2","ack":"C","tail":"N8643A","flight":"WN4667","msgno":"S35A"}\n'
```

```
[vdlm2dec] 2020/12/08 21:05:16 {"timestamp":1607461516.184175,"station_id":"CS-KABQ-VDLM","channel":2,"freq":136.975,"icao":10512364,"toaddr":1053386,"is_response":1,"is_onground":0}
[webapp] 2020/12/08 21:05:16 [vdlm2 data] b'{"timestamp":1607461516.184175,"station_id":"CS-KABQ-VDLM","channel":2,"freq":136.975,"icao":10512364,"toaddr":1053386,"is_response":1,"is_onground":0}\n'
[vdlm2dec] 2020/12/08 21:05:17 {"timestamp":1607461517.118571,"station_id":"CS-KABQ-VDLM","channel":2,"freq":136.975,"icao":11269048,"toaddr":1053386,"is_response":1,"is_onground":0}
[webapp] 2020/12/08 21:05:17 [2020-12-08 21:05:17 +0000] [370] [ERROR] Error handling request /socket.io/?EIO=3&transport=polling&t=1607461517079-11&sid=e813bbeb08cc4fa9b29eb19d95b2b817
[webapp] 2020/12/08 21:05:17 Traceback (most recent call last):
[webapp] 2020/12/08 21:05:17   File "/usr/lib/python3/dist-packages/gunicorn/workers/sync.py", line 135, in handle
[webapp] 2020/12/08 21:05:17     self.handle_request(listener, req, client, addr)
[webapp] 2020/12/08 21:05:17   File "/usr/lib/python3/dist-packages/gunicorn/workers/sync.py", line 176, in handle_request
[webapp] 2020/12/08 21:05:17     respiter = self.wsgi(environ, resp.start_response)
[webapp] 2020/12/08 21:05:17   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2464, in __call__
[webapp] 2020/12/08 21:05:17     return self.wsgi_app(environ, start_response)
[webapp] 2020/12/08 21:05:17   File "/usr/local/lib/python3.7/dist-packages/flask_socketio/__init__.py", line 46, in __call__
[webapp] 2020/12/08 21:05:17     start_response)
[webapp] 2020/12/08 21:05:17   File "/usr/local/lib/python3.7/dist-packages/engineio/middleware.py", line 60, in __call__
[webapp] 2020/12/08 21:05:17     return self.engineio_app.handle_request(environ, start_response)
[webapp] 2020/12/08 21:05:17   File "/usr/local/lib/python3.7/dist-packages/socketio/server.py", line 563, in handle_request
[webapp] 2020/12/08 21:05:17     return self.eio.handle_request(environ, start_response)
[webapp] 2020/12/08 21:05:17   File "/usr/local/lib/python3.7/dist-packages/engineio/server.py", line 416, in handle_request
[webapp] 2020/12/08 21:05:17     socket = self._get_socket(sid)
[webapp] 2020/12/08 21:05:17   File "/usr/local/lib/python3.7/dist-packages/engineio/server.py", line 609, in _get_socket
[webapp] 2020/12/08 21:05:17     raise KeyError('Session is disconnected')
[webapp] 2020/12/08 21:05:17 KeyError: 'Session is disconnected'
[webapp] 2020/12/08 21:05:17 [vdlm2 data] b'{"timestamp":1607461517.118571,"station_id":"CS-KABQ-VDLM","channel":2,"freq":136.975,"icao":11269048,"toaddr":1053386,"is_response":1,"is_onground":0}\n'
[webapp] 2020/12/08 21:05:17 Invalid session e813bbeb08cc4fa9b29eb19d95b2b817 (further occurrences of this error will be logged with level INFO)
[vdlm2dec] 2020/12/08 21:05:17 {"timestamp":1607461517.5771129,"station_id":"CS-KABQ-VDLM","channel":2,"freq":136.975,"icao":11261371,"toaddr":1066154,"is_response":0,"is_onground":0,"mode":"2","label":"H1","block_id":"3","ack":"!","tail":"N8616C","flight":"WN2395","msgno":"F42A","text":"#M1B/BA USADCXA.DR1.N8616C9CD9"}
```

```
[webapp] 2020/12/08 22:05:05 [vdlm2 data] b'{"timestamp":1607465105.8807731,"station_id":"CS-KABQ-VDLM","channel":2,"freq":136.975,"icao":11139997,"toaddr":1053386,"is_response":1,"is_onground":0}\n'
[webapp] 2020/12/08 22:05:07 [2020-12-08 22:05:07 +0000] [370] [ERROR] Error handling request /socket.io/?EIO=3&transport=polling&t=1607465107061-19826&sid=0aa97f0859f544418608c01dde259875
[webapp] 2020/12/08 22:05:07 Traceback (most recent call last):
[webapp] 2020/12/08 22:05:07   File "/usr/lib/python3/dist-packages/gunicorn/workers/sync.py", line 135, in handle
[webapp] 2020/12/08 22:05:07     self.handle_request(listener, req, client, addr)
[webapp] 2020/12/08 22:05:07   File "/usr/lib/python3/dist-packages/gunicorn/workers/sync.py", line 176, in handle_request
[webapp] 2020/12/08 22:05:07     respiter = self.wsgi(environ, resp.start_response)
[webapp] 2020/12/08 22:05:07   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2464, in __call__
[webapp] 2020/12/08 22:05:07     return self.wsgi_app(environ, start_response)
[webapp] 2020/12/08 22:05:07   File "/usr/local/lib/python3.7/dist-packages/flask_socketio/__init__.py", line 46, in __call__
[webapp] 2020/12/08 22:05:07     start_response)
[webapp] 2020/12/08 22:05:07   File "/usr/local/lib/python3.7/dist-packages/engineio/middleware.py", line 60, in __call__
[webapp] 2020/12/08 22:05:07     return self.engineio_app.handle_request(environ, start_response)
[webapp] 2020/12/08 22:05:07   File "/usr/local/lib/python3.7/dist-packages/socketio/server.py", line 563, in handle_request
[webapp] 2020/12/08 22:05:07     return self.eio.handle_request(environ, start_response)
[webapp] 2020/12/08 22:05:07   File "/usr/local/lib/python3.7/dist-packages/engineio/server.py", line 396, in handle_request
[webapp] 2020/12/08 22:05:07     socket = self._get_socket(sid)
[webapp] 2020/12/08 22:05:07   File "/usr/local/lib/python3.7/dist-packages/engineio/server.py", line 609, in _get_socket
[webapp] 2020/12/08 22:05:07     raise KeyError('Session is disconnected')
[webapp] 2020/12/08 22:05:07 KeyError: 'Session is disconnected'
[vdlm2dec] 2020/12/08 22:05:12 {"timestamp":1607465112.33723,"station_id":"CS-KABQ-VDLM","channel":2,"freq":136.975,"icao":10758676,"toaddr":1057098,"is_response":0,"is_onground":0,"mode":"2","label":"_d","block_id":"8","ack":"D","tail":"N368AR","flight":"AM0659","msgno":"S75A"}
```

**Comment by fredclausen** [comment]
Had a brain wave and checked my saved logs of ACARS/VDLM messages from the last couple of weeks.  There aren't many, but there are some, messages that are more than 1024 characters in length. I assume that since the socket receive buffer is 1024 bytes, everything else in that message more than 1024 bytes is dropped?

If that's true, that would explain the occasional "invalid json" because some of the json file is never received. I've upped the receive buffer size to see if this fixes that traceback.

**Comment by mikenye** [comment]
FYI, created branch `issue_5` for troubleshooting this. I've upped the receive buffer size to the maximum UDP datagram size (65527) which should hopefully solve that issue.

As a further enhancement, we should wrap the `json.loads(data)` in a `try: ... except: ...` to catch the error, perform some logging and fail gracefully.

**Comment by mikenye** [comment]
FYI, just caught it stop responding:

```json
{"timestamp":1607489329.299067,"station_id":"MN-YPPH1-ACARS","channel":0,"freq":131.550,"level":-24,"error":0,"mode":"2","label":"BA","block_id":"7","ack":false,"tail":"VH-QPI","flight":"QF0778","msgno":"J14A","text":"/MELCAYA.AT1.VH-QPI20930BCC3D9F3BA01FF744504C31002528B4A7CE2D025293126453CA9545100B423338CDC2448B3295525A0A54307A","libacars":{"arinc622":{"msg_type":"fans1a_cpdlc_msg","crc_ok":true,"gs_addr":"MELCAYA","air_addr":".VH-QPI","cpdlc":{"err":false,"atc_downlink_msg":{"header":{"msg_id":1,"timestamp":{"hour":4,"min":48,"sec":47}},"atc_downlink_msg_element_id":{"choice_label":"POSITION REPORT [positionreport]","choice":"dM48PositionReport","data":{"pos_report":{"pos_current":{"choice":"latitudeLongitude","data":{"lat_lon":{"lat":{"deg":32,"min":12.700000,"dir":"south"},"lon":{"deg":116,"min":27.600000,"dir":"east"}}}},"time_at_pos_current":{"hour":4,"min":48},"alt":{"choice":"altitudeFlightLevel","data":{"flight_level":158}},"next_fix":{"choice":"fixName","data":{"fix":"RERON"}},"eta_at_fix_next":{"hour":5,"min":40},"next_next_fix":{"choice":"fixName","data":{"fix":"RIDLE"}},"eta_at_dest":{"hour":7,"min":37},"temp":{"choice":"temperatureC","data":{"temp_deg_c":{"val":-6.000000,"unit":"C"}}},"winds":{"wind_dir":{"val":326.000000,"unit":"deg"},"wind_speed":{"choice":"windSpeedEnglish","data":{"wind_speed_english":{"val":32.000000,"unit":"kts"}}}},"speed":{"choice":"spee'
```

Note the JSON is cut off...

I'll look into this, just documenting here for posterity.

**Comment by mikenye** [comment]
Note regarding new healthcheck script - checking feeders needs wrapping in `if [ -n "$FEED" ]...`.

**Comment by fredclausen** [comment]
Some more JSON cut off. Not sure if it is helpful but I thought I'd pop it in here

```
[acars data] Error with JSON input b'{"timestamp":1607536203.2633989,"station_id":"CS-KABQ-ACARS","channel":0,"freq":130.025,"level":-24,"error":0,"mode":"2","label":"H1","block_id":"6","ack":false,"tail":"N18243","flight":"UA0642","msgno":"D14G","text":"HYDN18243091220KEWRKSAN06424200 70000000000003G86700 -27.0 85.38 8\\r\\n5.31 90.84 90.69 -55.0  380000.799122120 72720 70.8 81.830883048   0.\\r\\n000   0.000---AIRFALSE -27.3 85.38 85.38 90.91 90.75 -55.0  380000.79\\r\\n8122120 72725 70.8 81.830883048   0.000   0.000---AIRFALSE -27.3 85.4\\r\\n7 85.56 90.94 90.84 -55.0  379990.798122120 72730 70.8 81.830883048  \\r\\n 0.000   0.000---AIRFALSE -27.5 85.41 85.50 90.84 90.81 -55.0  380000\\r\\n.797122120 72735 70.8 81.830883048   0.000   0.000---AIRFALSE -27.5 8\\r\\n5.38 85.50 90.81 90.84 -55.3  380040.797122120 72740 70.8 81.83088304\\r\\n8   0.000   0.000---AIRFALSE -27.5 85.44 85.53 90.88 90.81 -55.0  380\\r\\n030.796122120 72745 70.8 81.830883048   0.000   0.000---AIRFALSE -27.\\r\\n5 85.47 85.41 90.84 90.84 -55.3  380030.796122120 72750 70.8 81.83088\\r\\n3048   0.000   0.000---AIRFALSE -27.5 85.50 85.50 90.91 90.84 -55.0  \\r\\n380000.796122120 72755 70.8 81.830883048   0.000   0.000---AIRFALSE -\\r\\n27.5 85.53 85.41 90.91 90.75 -55.0  380000.796122120 72760 70.8 81.83\\r\\n0883048   0.000   0.000---AIRFALSE -27.5 85.41 85.38 90.84 90.75 -55.\\r\\n0  379990.795122120 72769 70.8 81.830883048   0.000   0.000---AIRFALS\\r\\nE -27.3 87.09 87' .
```

**Comment by fredclausen** [comment]
I've added

`data,addr = acars_receiver.recvfrom(65527, socket.MSG_WAITALL)`

in to application.py. My thinking is there is something weird here about packet size that the decoders are sending and python not waiting for the entire message to be received. I think, from my reading, this should help/fix that.

This could also be a bug in acarsdec/vdlm2dec where a message gets too large and it just doesn't send it. I have this change running on my test machine and I'll see if it kicks any errors out.

**Comment by fredclausen** [comment]
[acarsdec](https://github.com/TLeconte/acarsdec/blob/966126da1cb4cf12ab5a5eb6a26ce6f63e069e08/output.c#L323) source code specifies a buffer of 1400 bytes for writing JSON, and the message gets truncated if above that, if I am reading this right.

Trying to track down for vdlm2dec handles this.

**Comment by fredclausen** [comment]
Double checked VDLM and the code suggests the buffer it uses for VDLM messages is 50000 characters, and my logs are showing messages from VDLM of well over 2400 characters, so I don't think VDLM is going to give us any fits over this. In fact, I think it definitely points the finger at acarsdec as being the culprit for cutting off the messages in the first place.

I've added a sed statement in the Dockerfile to expand what looks to me to be the internal buffer that was used for the socket. It uses a buffer of 3600 characters all throughout the file for storing JSON data, but only for the socket write did it drop down to 1400 characters. Waiting to see a large message come through to validate my fix.

I am curious if it would be worth expanding the buffer size all throughout the program if this proves out?

**Comment by mikenye** [comment]
Good find! I don't know enough C to answer that, but it's worth a try!

**Comment by fredclausen** [comment]
Looks like the fix for the truncated ACARS JSON works.

However, I cannot figure out the disconnect traceback error. I suspect it might be something unique to my setup if you aren't seeing similar things. My googling suggests the error is caused because the server doesn't receive a ping message from the client and times out the connection, but the client is still there and eventually sends another ping message that the server gets, and doesn't know who that session is because it was already timed out. Then it dumps a traceback. The javascript log in Safari shows error 500, and I believe 400 as well. I might be wrong on the exact 40x code; I'll double check next time.

I've tried upping the socket time out, changing the javascript connection from http to ws to see if for some reason it never updated the connection to a proper web socket from the initial polling connection I believe it establishes (explaining it poorly, sorry. I'm at the edge of my understanding of what is going on).

To give an idea how I am running this: on my k3s cluster, Safari on a Mac, and I leave the tab open. The traceback errors appear at random, sometimes going hours between and sometimes they happen in quick succession.

One possible bottleneck here is the application gets the ping packet/packet never makes it over from the client because it is blocked from doing anything because the application is working on something else. While the application is doing something else, Gunicorn ends up marking the connection as disconnected. This might because we are running this on Pis, or maybe there is a threading issue.

I'm not sure, honestly, and like I said, I've reached the edge of my understanding. I'll keep poking at it.

**Comment by mikenye** [comment]
Hi @fredclausen, I've had exactly the same errors (although infrequent). The client just starts working again shortly after, and doesn't appear to miss any messages.

**Comment by mikenye** [comment]
FYI I had a long message this morning and it appeared to recover just fine:

```
[webapp] 2020/12/12 07:17:17 [acars data] Error with JSON input b'{"timestamp":1607728637.0700059,"station_id":"MN-YPPH1-ACARS","channel":0,"freq":131.550,"level":-18,"error":0,"mode":"2","label":"H1","block_id":"8","ack":false,"tail":"VH-NXL","flight":"QF1970","msgno":"D06G","text":"/AETR.\\r\\nTKO/43A01\\r\\n55093111220231638001970PERKFENJ1701000044000\\r\\n00555024716220268095960024300001100000110100067\\r\\n138413771523138408840927073006742002590008513291\\r\\n138313771523137208790925074006705002580008513382\\r\\n0830930071443150302693883056821050247\\r\\n0810940071443150302693896056321020251\\r\\n025202520000-00002710618108127025033\\r\\n025202540000000002750606066067037199\\r\\n0006128000000006030000000000000002300000\\r\\n0006028000000006230000000000000002300000\\r\\n06230263\\r\\n06210263\\r\\n02846\\r\\n2307371387135713851357017292480273055502AAC0000000000\\r\\n23083613431348135013480342536902750500028000000000000\\r\\n23093613671375137813750654042302250500028000000000000\\r\\n23103613871399140113990974545101880500028000000000000\\r\\n23113613721387138813871196052102080500028000000000000\\r\\n23123613791396139713961419156501980500028000000000000\\r\\n23133614051425142714251658359701580500028000000000000\\r\\n23143614131434143414341884362201400500028000000000000\\r\\n23153614291450145114502098564501130500028000000000000\\r\\n23163614411463146514632258666600900500028000000000000\\r\\n060009000001000\\r\\n2307370886088009280927000011000001101\\r\\n2308360870086809210922000011000001101\\r\\n' .
```

**Comment by fredclausen** [comment]
@mikenye interesting. Was this with the buffer fix?
